manifest:
  remotes:
    # - name: zmkfirmware
      url-base: https://github.com/petejohanson
    # - name: badjeff
      url-base: https://github.com/badjeff
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: feat/pointers-move-scroll
    #   import: app/west.yml
    # - name: zmk-pmw3610-driver
    #   remote: badjeff
    #  revision: main
    - name: zmk-fingerpunch-vik
      remote: sadekbaroudi
      revision: main
      import: config/deps.yml
  self:
    path: config